# Generated by Django 5.0.4 on 2024-07-03 18:06

from django.db import migrations


class Migration(migrations.Migration):
    def set_rarity_of_items(apps, schema_editor):
        item_model = apps.get_model('main_app', 'Item')


        for item in item_model.objects.all():
            if item.price <= 10:
                item.rarity = 'Rare'
            elif item.price <= 20:
                item.rarity = 'Very Rare'
            elif item.price <= 30:
                item.rarity = 'Extremely Rare'
            else:
                item.rarity = 'Mega Rare'

    def set_rarity_of_items_default(apps, schema_editor):
        item_model = apps.get_model('main_app', 'Item')

        for item in item_model.objects.all():
            item.rarity = item_model._meta.get_field('rarity').default
            item.save()

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity_of_items, set_rarity_of_items_default)
    ]
