# Generated by Django 5.0.4 on 2024-07-03 18:23

from django.db import migrations


def set_new_price(apps, schema_editor):
    MULTIPLIER = 120
    smartphone = apps.get_model('main_app', 'Smartphone')

    for phone in smartphone.objects.all():
        phone.price = MULTIPLIER * len(phone.brand)
        phone.save()


def set_category(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')

    for phone in smartphone.objects.all():
        if phone.price >= 750:
            phone.category = 'Expensive'
        else:
            phone.category = 'Cheap'
        phone.save()


def reverse_category_and_price(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')

    for phone in smartphone.objects.all():
        phone.price = smartphone._meta.get_field('price').default
        phone.category = smartphone._meta.get_field('category').default
        phone.save()


def set_price_and_category(apps, schema_editor):
    set_new_price(apps, schema_editor)
    set_category(apps, schema_editor)

class Migration(migrations.Migration):



    dependencies = [
        ('main_app', '0013_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_price_and_category, reverse_category_and_price)
    ]

