# Generated by Django 5.0.4 on 2024-07-17 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_zoodisplayanimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zookeeper',
            name='specialty',
            field=models.CharField(choices=[('Mammals', 'Mammals'), ('Bird', 'Bird'), ('Reptiles', 'Reptiles'), ('Others', 'Others')], max_length=10),
        ),
    ]
