# Generated by Django 5.0.4 on 2024-07-06 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_artifact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artifact',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
