# Generated by Django 5.0.4 on 2024-06-29 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_project_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_edited_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
