# Generated by Django 5.0.4 on 2024-07-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_song_artist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='song',
            new_name='songs',
        ),
    ]
