# Generated by Django 5.0.4 on 2024-06-30 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id_available',
            new_name='is_available',
        ),
    ]
